server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: java-rest-api
  threads:
    virtual:
      enabled: true # Java 21 Virtual Threads enabled for all HTTP requests and async jobs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
